// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class fix_NewResistanceMb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_NewResistanceMb));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091651103_fix_NewResistanceMb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
