////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$AddTitle", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.GameMaster, AuthorityType.SuperModerator })]
    public class AddTitlePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short TitleVnum { get; set; }

        [PacketIndex(1)]
        public byte TitleId { get; set; }

        public static string ReturnHelp() => "$AddTitle VNUM ID";

        #endregion
    }
}