////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$MapDance", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.TrialGameMaster, AuthorityType.TeamManager } )]
    public class MapDancePacket : PacketDefinition
    {
        public static string ReturnHelp() => "$MapDance";
    }
}